FROM node:16-alpine as builder
WORKDIR /
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build


FROM nginx:stable-alpine
COPY --from=builder /build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]

