version: "3.4"
networks:
  web:
services:
  frontend:
    image: frontend:latest
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    ports:
      - "81:80"
    networks:
      - web

  backend:
    image: backend:latest
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    expose:
      - 8080
    networks:
      - web