FROM maven AS build
WORKDIR /app
COPY . .
RUN mvn clean install -DSkipTests

FROM openjdk
COPY --from=build /app/target/SpringBoot-1.0.0-SNAPSHOT.jar /app.jar
COPY --from=build /app/tmp/ /tmp
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]
