FROM maven:3.6.0-jdk-11-slim AS build
WORKDIR /app
COPY ../backend/src .
COPY ../backend/pom.xml .
RUN mvn -f /app/pom.xml clean package

FROM openjdk:11-jre-slim
COPY --from=build /app/target/SpringBoot-0.0.1-SNAPSHOT.jar /app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]