FROM node:16 as builder
WORKDIR /app
COPY ../frontend/package*.json /app/
RUN npm install
COPY ../frontend/ /app/
RUN npm run build

FROM nginx
COPY --from=builder /app/build/ /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf